//
//  SourcesReferencesView.swift
//  Ethica
//
//  Shows the real-world sources behind health scores, additive risk ratings,
//  and recommendations surfaced in the scan feature. Reachable from every
//  scan result screen so citations are easy for users to find.
//

import SwiftUI

struct SourcesReferencesView: View {
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: Spacing.lg) {
                    VStack(alignment: .leading, spacing: Spacing.sm) {
                        Text("How we assess products")
                            .font(Typography.h3)
                            .foregroundColor(Theme.textPrimary)

                        Text("Health scores, additive risk ratings, and recommendations are generated by AI and cross-referenced against the public health sources below. This information is for educational purposes only and is not medical advice — always consult a doctor, registered dietitian, or allergist for health decisions.")
                            .font(Typography.body)
                            .foregroundColor(Theme.textSecondary)
                    }
                    .padding(Spacing.md)
                    .background(Theme.surfaceSecondary)
                    .clipShape(RoundedRectangle(cornerRadius: Spacing.radiusSM))

                    VStack(alignment: .leading, spacing: Spacing.sm) {
                        Text("Sources")
                            .font(Typography.h3)
                            .foregroundColor(Theme.textPrimary)

                        VStack(spacing: Spacing.sm) {
                            ForEach(CitationLibrary.all) { source in
                                citationRow(source)
                            }
                        }
                    }
                }
                .padding(Spacing.screenHorizontal)
                .padding(.vertical, Spacing.lg)
            }
            .background(Theme.backgroundPrimary)
            .navigationTitle("Sources & References")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") { dismiss() }
                        .foregroundColor(Theme.primary)
                }
            }
        }
    }

    private func citationRow(_ source: CitationSource) -> some View {
        Link(destination: source.url) {
            HStack(alignment: .top, spacing: Spacing.sm) {
                Image(systemName: "link.circle.fill")
                    .font(.system(size: 20))
                    .foregroundColor(Theme.primary)

                VStack(alignment: .leading, spacing: 2) {
                    Text(source.name)
                        .font(.system(size: 14, weight: .semibold))
                        .foregroundColor(Theme.textPrimary)

                    Text(source.organization)
                        .font(.system(size: 12, weight: .medium))
                        .foregroundColor(Theme.primary)

                    Text(source.summary)
                        .font(.system(size: 12))
                        .foregroundColor(Theme.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                }

                Spacer()

                Image(systemName: "arrow.up.right.square")
                    .font(.system(size: 14))
                    .foregroundColor(Theme.textMuted)
            }
            .padding(Spacing.sm)
            .background(
                RoundedRectangle(cornerRadius: 10)
                    .fill(.ultraThinMaterial)
                    .overlay(
                        RoundedRectangle(cornerRadius: 10)
                            .stroke(Color.white.opacity(0.08), lineWidth: 1)
                    )
            )
        }
        .buttonStyle(.plain)
        .accessibilityElement(children: .combine)
        .accessibilityHint("Opens \(source.organization) in your browser")
    }
}

#Preview {
    SourcesReferencesView()
}
